# Generated by Django 4.0.5 on 2022-06-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('paid_by', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=256)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
